#!/usr/bin/env python3
"""Generate the UI stack's secrets and write both environment files.

Why a script rather than hand-edited values:

* **Consistency is a correctness property.** The Keycloak client secret lives in two
  places — the realm import (as ``MONI_UI_WEB_CLIENT_SECRET``) and LibreChat's
  ``OPENID_CLIENT_SECRET``. Generating them separately is how they drift, and the symptom
  is an unexplained 401 at login.
* **LibreChat ships usable-looking defaults** for ``CREDS_KEY``/``CREDS_IV``/``JWT_SECRET``/
  ``JWT_REFRESH_SECRET``. They are published in the upstream repository, so copying them
  would make stored credentials and session cookies forgeable (§3.11). Generating is the
  only safe option, and a script makes that the path of least resistance.

Writes:

* the UI block of the root ``.env``        (compose substitution: ports, passwords)
* ``ui/.env``                              (the container's own env_file)

Both are git-ignored. ``ui/.env`` is written as UTF-8 without a BOM, which matters because
PowerShell's ``>`` redirection produces UTF-16 and a BOM corrupts the first key.

Usage::

    uv run --group dev python scripts/gen_ui_secrets.py          # write both files
    uv run --group dev python scripts/gen_ui_secrets.py --force  # overwrite existing secrets
"""

from __future__ import annotations

import argparse
import base64
import secrets
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ROOT_ENV = REPO_ROOT / ".env"
UI_ENV = REPO_ROOT / "ui" / ".env"

BLOCK_HEADER = "# MONI AI UI — LibreChat fork (task 1.4)"

#: Secrets the script generates. The key is the variable name; the value is how to make it.
GENERATORS: dict[str, str] = {
    "MONI_UI_WEB_CLIENT_SECRET": "token_urlsafe",
    "UI_MONGO_PASSWORD": "token_hex32",
    "UI_MEILI_MASTER_KEY": "token_hex32",
    "UI_CREDS_KEY": "token_hex32",
    "UI_CREDS_IV": "token_hex16",
    "UI_JWT_SECRET": "token_hex32",
    "UI_JWT_REFRESH_SECRET": "token_hex32",
    "UI_SESSION_SECRET": "token_urlsafe",
}


def make(kind: str) -> str:
    if kind == "token_hex32":
        return secrets.token_hex(32)
    if kind == "token_hex16":
        return secrets.token_hex(16)
    if kind == "token_urlsafe":
        return secrets.token_urlsafe(32)
    if kind == "b64":
        return base64.b64encode(secrets.token_bytes(32)).decode()
    msg = f"unknown generator {kind!r}"
    raise ValueError(msg)


def read_env(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and "=" in stripped:
            key, _, value = stripped.partition("=")
            values[key.strip()] = value.strip()
    return values


def root_block(values: dict[str, str], port: str) -> str:
    return f"""
# =============================================================================
{BLOCK_HEADER}
#
# Generated by scripts/gen_ui_secrets.py — re-run it rather than editing values here.
# Regenerating CHANGES the client secret, so the Keycloak realm must be re-imported
# afterwards (see docs/runbooks/ui.md).
# =============================================================================

# Host port for the UI, published on 127.0.0.1 only (§3.1).
UI_PORT={port}

# Confidential Keycloak client secret. Must match OPENID_CLIENT_SECRET in ui/.env and the
# moni-ui-web client in the imported realm.
MONI_UI_WEB_CLIENT_SECRET={values["MONI_UI_WEB_CLIENT_SECRET"]}

# UI datastores. Neither publishes a host port (§3.1).
UI_MONGO_PASSWORD={values["UI_MONGO_PASSWORD"]}
UI_MEILI_MASTER_KEY={values["UI_MEILI_MASTER_KEY"]}

# LibreChat credential encryption + session signing (upstream defaults are published).
UI_CREDS_KEY={values["UI_CREDS_KEY"]}
UI_CREDS_IV={values["UI_CREDS_IV"]}
UI_JWT_SECRET={values["UI_JWT_SECRET"]}
UI_JWT_REFRESH_SECRET={values["UI_JWT_REFRESH_SECRET"]}
UI_SESSION_SECRET={values["UI_SESSION_SECRET"]}
"""


def ui_env(values: dict[str, str], template: Path) -> str:
    """The container's env file: the template with every generated value substituted.

    Every placeholder below is asserted to exist. A silently-unreplaced placeholder is the
    worst outcome here: the container starts, and the failure surfaces much later as an
    authentication error that names nothing useful (Mongo answering "requires
    authentication", or Keycloak rejecting a login).
    """
    text = template.read_text(encoding="utf-8")

    replacements = {
        "MEILI_MASTER_KEY=change-me-generate-with-openssl-rand-hex-32": (
            f"MEILI_MASTER_KEY={values['UI_MEILI_MASTER_KEY']}"
        ),
        # The URI must carry the same password compose uses to create the root user.
        "MONGO_URI=mongodb://moni:change-me-must-match-UI_MONGO_PASSWORD@ui-mongodb:27017/LibreChat?authSource=admin": (
            "MONGO_URI=mongodb://moni:"
            f"{values['UI_MONGO_PASSWORD']}@ui-mongodb:27017/LibreChat?authSource=admin"
        ),
        "CREDS_KEY=change-me-32-bytes-hex-64-chars": f"CREDS_KEY={values['UI_CREDS_KEY']}",
        "CREDS_IV=change-me-16-bytes-hex-32-chars": f"CREDS_IV={values['UI_CREDS_IV']}",
        "JWT_SECRET=change-me-32-bytes-hex-64-chars": f"JWT_SECRET={values['UI_JWT_SECRET']}",
        "JWT_REFRESH_SECRET=change-me-32-bytes-hex-64-chars": (
            f"JWT_REFRESH_SECRET={values['UI_JWT_REFRESH_SECRET']}"
        ),
        "OPENID_CLIENT_SECRET=change-me-must-match-MONI_UI_WEB_CLIENT_SECRET": (
            f"OPENID_CLIENT_SECRET={values['MONI_UI_WEB_CLIENT_SECRET']}"
        ),
        "OPENID_SESSION_SECRET=change-me-32-bytes-hex-64-chars": (
            f"OPENID_SESSION_SECRET={values['UI_SESSION_SECRET']}"
        ),
    }
    for old, new in replacements.items():
        if old not in text:
            msg = f"ui.env.example no longer contains {old!r}; the generator is out of date"
            raise SystemExit(msg)
        text = text.replace(old, new)

    banner = (
        "# GENERATED from infra/ui/ui.env.example by scripts/gen_ui_secrets.py.\n"
        "# Real dev secrets live here; this file is git-ignored. Explanations: see the\n"
        "# template, which is the reviewable source of truth.\n"
    )
    return banner + text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="gen_ui_secrets", description=__doc__)
    parser.add_argument(
        "--force",
        action="store_true",
        help="regenerate even when the values already exist (invalidates the realm secret)",
    )
    parser.add_argument("--ui-port", default="3080", help="host port for the UI (default 3080)")
    args = parser.parse_args(argv)

    existing = read_env(ROOT_ENV)
    values: dict[str, str] = {}
    for name, kind in GENERATORS.items():
        current = existing.get(name)
        if current and "change-me" not in current and not args.force:
            values[name] = current
        else:
            values[name] = make(kind)

    # Root .env: replace an existing block, or append one.
    root_text = ROOT_ENV.read_text(encoding="utf-8") if ROOT_ENV.is_file() else ""
    if BLOCK_HEADER in root_text:
        head, _, _ = root_text.partition("\n# ============")
        # Drop everything from the UI block's opening rule onward, then re-append.
        marker_index = root_text.index("# ============", root_text.index(BLOCK_HEADER) - 400)
        keep = root_text[:marker_index].rstrip("\n")
        del head
        root_text = keep
    ROOT_ENV.write_text(
        root_text.rstrip("\n") + root_block(values, args.ui_port), encoding="utf-8", newline="\n"
    )

    template = REPO_ROOT / "infra" / "ui" / "ui.env.example"
    UI_ENV.write_text(ui_env(values, template), encoding="utf-8", newline="\n")

    for path in (ROOT_ENV, UI_ENV):
        raw = path.read_bytes()
        if raw[:3] == b"\xef\xbb\xbf":
            sys.stdout.write(f"WARNING: {path.name} has a BOM\n")
    sys.stdout.write(
        f"wrote {ROOT_ENV.relative_to(REPO_ROOT)} and {UI_ENV.relative_to(REPO_ROOT)} "
        f"({len(GENERATORS)} secrets; {'regenerated' if args.force else 'reused existing'})\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
